site_name: lke-operator
repo_url: https://github.com/anza-labs/lke-operator

copyright: >-
  Copyright &copy;
  <script>
    document.write(new Date().getFullYear())
  </script>
  lke-operator contributors

plugins:
- search
- mkdocs-nav-weight

markdown_extensions:
- admonition
- attr_list
- footnotes
- md_in_html
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- tables

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png

  custom_dir: docs/overrides

  features:
  - navigation.tabs
  - header.autohide
  - search.suggest
  - search.highlight

  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue grey
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue grey
    toggle:
      icon: material/weather-night
      name: Switch to light mode

extra:
  version:
    provider: mike
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
