resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- lkeclusterconfig_editor_role.yaml
- lkeclusterconfig_viewer_role.yaml
