# permissions for end users to view lkeclusterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lke-operator
    app.kubernetes.io/managed-by: kustomize
  name: lkeclusterconfig-viewer-role
rules:
- apiGroups:
  - lke.anza-labs.dev
  resources:
  - lkeclusterconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lke.anza-labs.dev
  resources:
  - lkeclusterconfigs/status
  verbs:
  - get
