---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - lke.anza-labs.dev
  resources:
  - lkeclusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lke.anza-labs.dev
  resources:
  - lkeclusterconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - lke.anza-labs.dev
  resources:
  - lkeclusterconfigs/status
  verbs:
  - get
  - patch
  - update
