name: Remove Label

on: [issue_comment]

jobs:
  remove_label:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.comment.body, '/ok-to-test') && github.event.issue.pull_request }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          gh pr checkout ${{ github.event.issue.number }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: false
      - uses: helm/kind-action@v1
      - uses: docker/build-push-action@v5
        with:
          tags: ghcr.io/${{ github.event.repository.owner.name }}/lke-operator:e2e
          build-args: VERSION=${{ github.ref_name }}
      - run: |
          kind load docker-image ghcr.io/${{ github.event.repository.owner.name }}/lke-operator:e2e
      - run:
          make install
          make deploy IMG=ghcr.io/${{ github.event.repository.owner.name }}/lke-operator:e2e
      - run: |
          make test-e2e
