name: go

on:
  pull_request:
    branches: [ '*' ]
    paths:
      - 'api/**'
      - 'cmd/**'
      - 'hack/templates/**'
      - 'hack/*.go'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
  push:
    branches:
      - "main"

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: false
      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          skip-cache: true

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: false
      - run: |
          make test
