name: image-docs

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3
      - id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.event.repository.owner.name }}/lke-operator:${{ github.ref_name }}
          build-args: VERSION=${{ github.ref_name }}

  release-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true
      - run: |
          pip install poetry
      - run: |
          poetry install
      - run: |
          poetry run publish --version "${{ github.ref_name }}"
