name: publish-docs

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true
      - run: |
          pip install poetry
      - run: |
          poetry install
      - run: |
          poetry run publish --version "${{ github.ref_name }}"
